package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "object_catalog", schema = "public"
)
public class ObjectCatalog implements java.io.Serializable {


  private long ocId;
  private String name;
  private String path;
  private Date dateUt;
  private String camName;
  private String skyName;
  private Long tcId;
  private Boolean isUpload;
  private Boolean isProcess;

  public ObjectCatalog() {
  }

  public ObjectCatalog(int ocId) {
    this.ocId = ocId;
  }


  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "oc_id_seq")})
     @Id 
  @GeneratedValue(generator = "generator")
  @Column(name = "oc_id", unique = true, nullable = false)
  public long getOcId() {
    return this.ocId;
  }

  public void setOcId(long ocId) {
    this.ocId = ocId;
  }

  @Column(name = "name")
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  /**
   * @return the path
   */
  @Column(name = "path")
  public String getPath() {
    return path;
  }

  /**
   * @param path the path to set
   */
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * @return the dateUt
   */
  @Column(name = "date_ut")
  public Date getDateUt() {
    return dateUt;
  }

  /**
   * @param dateUt the dateUt to set
   */
  public void setDateUt(Date dateUt) {
    this.dateUt = dateUt;
  }

  /**
   * @return the camName
   */
  @Column(name = "cam_name")
  public String getCamName() {
    return camName;
  }

  /**
   * @param camName the camName to set
   */
  public void setCamName(String camName) {
    this.camName = camName;
  }

  /**
   * @return the skyName
   */
  @Column(name = "sky_name")
  public String getSkyName() {
    return skyName;
  }

  /**
   * @param skyName the skyName to set
   */
  public void setSkyName(String skyName) {
    this.skyName = skyName;
  }

  /**
   * @return the tcId
   */
  @Column(name = "tc_id")
  public Long getTcId() {
    return tcId;
  }

  /**
   * @param tcId the tcId to set
   */
  public void setTcId(Long tcId) {
    this.tcId = tcId;
  }
  
  /**
   * @return the isUpload
   */
  @Column(name = "is_upload")
  public Boolean getIsUpload() {
    return isUpload;
  }

  /**
   * @param isUpload the isUpload to set
   */
  public void setIsUpload(Boolean isUpload) {
    this.isUpload = isUpload;
  }

  /**
   * @return the isProcess
   */
  @Column(name = "is_process")
  public Boolean getIsProcess() {
    return isProcess;
  }

  /**
   * @param isProcess the isProcess to set
   */
  public void setIsProcess(Boolean isProcess) {
    this.isProcess = isProcess;
  }

}
