package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "template_catalog", schema = "public"
)
public class TemplateCatalog implements java.io.Serializable {


  private long tcId;
  private String name;
  private String path;
  private Date dateUt;
  private String camName;
  private String skyName;

  public TemplateCatalog() {
  }

  public TemplateCatalog(int tcId) {
    this.tcId = tcId;
  }


  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "tc_id_seq")})
     @Id 
  @GeneratedValue(generator = "generator")
  @Column(name = "tc_id", unique = true, nullable = false)
  public long getTcId() {
    return this.tcId;
  }

  public void setTcId(long tcId) {
    this.tcId = tcId;
  }

  @Column(name = "name")
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  /**
   * @return the path
   */
  @Column(name = "path")
  public String getPath() {
    return path;
  }

  /**
   * @param path the path to set
   */
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * @return the dateUt
   */
  @Column(name = "date_ut")
  public Date getDateUt() {
    return dateUt;
  }

  /**
   * @param dateUt the dateUt to set
   */
  public void setDateUt(Date dateUt) {
    this.dateUt = dateUt;
  }

  /**
   * @return the camName
   */
  @Column(name = "cam_name")
  public String getCamName() {
    return camName;
  }

  /**
   * @param camName the camName to set
   */
  public void setCamName(String camName) {
    this.camName = camName;
  }

  /**
   * @return the skyName
   */
  @Column(name = "sky_name")
  public String getSkyName() {
    return skyName;
  }

  /**
   * @param skyName the skyName to set
   */
  public void setSkyName(String skyName) {
    this.skyName = skyName;
  }

}
